name: Run code style checks

on:
  push:
    branches:
      - main
      - model
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run CodeStyle checks
        run: |
          pre-commit run check-yaml --all-files
          pre-commit run end-of-file-fixer --all-files
          pre-commit run trailing-whitespace --all-files
          pre-commit run requirements-txt-fixer --all-files
          pre-commit run black --all-files
