name: Run mypy types checks

on:
  push:
    branches:
      - main
      - model
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install mypy

      - name: Run mypy
        run: |
          pre-commit run mypy --all-files
